services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: gym-api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Default=Host=gym-postgres;Port=5432;Database=gymdb;Username=gymuser;Password=gympass
      - Jwt__Key=clave-secreta-muy-larga-para-gymapp-local-dev-32chars
      - Jwt__Issuer=GymApi
      - Jwt__Audience=GymApp
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - gym-net

networks:
  gym-net:
    external: true
