@GymApi_HostAddress = http://localhost:5211

### 1. Registrar usuario
POST {{GymApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Fran",
  "email": "fran@gymapp.com",
  "password": "Password123!"
}

###

### 2. Login (copia el token de la respuesta en @token)
POST {{GymApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "fran@gymapp.com",
  "password": "Password123!"
}

###

### --- Pega aquí el token recibido en el login ---
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmcmFuQGd5bWFwcC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiRnJhbiIsImV4cCI6MTc3NjU5MTUzNSwiaXNzIjoiR3ltQXBpIiwiYXVkIjoiR3ltQXBwIn0.bZNmhCZyk_BdimJ99t5PerppKFSPJ0ARDeJibqgUNGU

### 3. GET todos los ejercicios (requiere token)
GET {{GymApi_HostAddress}}/api/exercises
Accept: application/json
Authorization: Bearer {{token}}

###

### 4. POST crear ejercicio (requiere token)
POST {{GymApi_HostAddress}}/api/exercises
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Press banca",
  "muscleGroup": "Pecho",
  "description": "Ejercicio de empuje horizontal"
}

###

### 5. PUT editar ejercicio (requiere token)
PUT {{GymApi_HostAddress}}/api/exercises/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Press banca plano",
  "muscleGroup": "Pecho",
  "description": "Ejercicio de empuje horizontal con barra"
}

###

### 6. DELETE eliminar ejercicio (requiere token)
DELETE {{GymApi_HostAddress}}/api/exercises/1
Authorization: Bearer {{token}}

###
